name: Mirror to SourceCraft

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check environment
        run: |
          whoami
          pwd
          ls -la ~/

      - name: Debug secret
        run: |
          echo "key length: ${#SOURCECRAFT_SSH_KEY}"
        env:
          SOURCECRAFT_SSH_KEY: ${{ secrets.SOURCECRAFT_SSH_KEY }}
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SOURCECRAFT_SSH_KEY }}

      - name: Push to SourceCraft
        run: |
          git remote add sourcecraft git@sourcecraft.dev/05252/python-itmo-site_project.git
          git push -f sourcecraft main